version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:bionic
    steps:
      - checkout
      - run:
          name: Install deps
          command: dpkg --add-architecture i386 && apt-get update && apt-get install -y git cmake pkg-config libssl-dev:i386 libcurl4-openssl-dev g++-multilib libpng-dev:i386 libx11-dev:i386 libxi-dev:i386 libssl-dev libudev-dev:i386 libevdev-dev:i386 libegl1-mesa-dev:i386 libgl1-mesa-dev libssl-dev libuv1-dev libzip-dev libprotobuf-dev protobuf-compiler imagemagick software-properties-common
      - run:
          name: Install Qt 5.12
          command: add-apt-repository -y ppa:beineri/opt-qt-5.12.3-bionic && apt-get update && apt-get install -y qt512base qt512declarative qt512quickcontrols qt512quickcontrols2 qt512svg qt512webengine
      - run:
          name: Run the buildscript
          command: . /opt/qt512/bin/qt512-env.sh && ./build-client-ui.sh
      - store_artifacts:
          path: Minecraft_Bedrock_Edition_launcher-x86_64.AppImage
